<a href="https://colab.research.google.com/github/somcode14/E-Commerce-Sales-Customer-Behavior-Analysis/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("ML project started")

ML project started

In [106]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder, PolynomialFeatures
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error
from sklearn.metrics import accuracy_score, classification_report

In [109]:


file_path = "/content/ecommerce_customer_behavior_dataset.csv"
df = pd.read_csv(file_path)

df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_001337,CUST_01337,2023-01-01,27,Female,Bursa,Toys,54.28,1,0.00,54.28,Debit Card,Mobile,4,14,True,8,5
1,ORD_004885,CUST_04885,2023-01-01,42,Male,Konya,Toys,244.90,1,0.00,244.90,Credit Card,Mobile,11,3,True,3,3
2,ORD_004507,CUST_04507,2023-01-01,43,Female,Ankara,Food,48.15,5,0.00,240.75,Credit Card,Mobile,7,8,True,5,2
3,ORD_000645,CUST_00645,2023-01-01,32,Male,Istanbul,Electronics,804.06,1,229.28,574.78,Credit Card,Mobile,8,10,False,1,4
4,ORD_000690,CUST_00690,2023-01-01,40,Female,Istanbul,Sports,755.61,5,0.00,3778.05,Cash on Delivery,Desktop,21,10,True,7,4

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order_ID                  5000 non-null   object
 1   Customer_ID               5000 non-null   object
 2   Date                      5000 non-null   object
 3   Age                       5000 non-null   int64
 4   Gender                    5000 non-null   object
 5   City                      5000 non-null   object
 6   Product_Category          5000 non-null   object
 7   Unit_Price                5000 non-null   float64
 8   Quantity                  5000 non-null   int64
 9   Discount_Amount           5000 non-null   float64
 10  Total_Amount              5000 non-null   float64
 11  Payment_Method            5000 non-null   object
 12  Device_Type               5000 non-null   object
 13  Session_Duration_Minutes  5000 non-null   int64
 14  Pages_Viewed              5000 non-null   int64
 15  Is_Returning_Customer     5000 non-null   bool
 16  Delivery_Time_Days        5000 non-null   int64
 17  Customer_Rating           5000 non-null   int64
dtypes: bool(1), float64(3), int64(6), object(8)
memory usage: 669.1+ KB

In [111]:
df.isnull().sum().sum()

np.int64(0)

In [112]:
#Encode Categorical Columns
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['City'] = le.fit_transform(df['City'])
df['Product_Category'] = le.fit_transform(df['Product_Category'])
df['Payment_Method'] = le.fit_transform(df['Payment_Method'])
df['Device_Type'] = le.fit_transform(df['Device_Type'])

df['Is_Returning_Customer'] = df['Is_Returning_Customer'].astype(int)

df.head()

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,ORD_001337,CUST_01337,2023-01-01,27,0,3,7,54.28,1,0.00,54.28,3,1,4,14,1,8,5
1,ORD_004885,CUST_04885,2023-01-01,42,1,9,7,244.90,1,0.00,244.90,2,1,11,3,1,3,3
2,ORD_004507,CUST_04507,2023-01-01,43,0,1,4,48.15,5,0.00,240.75,2,1,7,8,1,5,2
3,ORD_000645,CUST_00645,2023-01-01,32,1,6,2,804.06,1,229.28,574.78,2,1,8,10,0,1,4
4,ORD_000690,CUST_00690,2023-01-01,40,0,6,6,755.61,5,0.00,3778.05,1,0,21,10,1,7,4

In [113]:
#Drop Unnecessary Columns
df = df.drop(['Order_ID','Customer_ID','Date'], axis=1)
df.head()

,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating
0,27,0,3,7,54.28,1,0.00,54.28,3,1,4,14,1,8,5
1,42,1,9,7,244.90,1,0.00,244.90,2,1,11,3,1,3,3
2,43,0,1,4,48.15,5,0.00,240.75,2,1,7,8,1,5,2
3,32,1,6,2,804.06,1,229.28,574.78,2,1,8,10,0,1,4
4,40,0,6,6,755.61,5,0.00,3778.05,1,0,21,10,1,7,4

In [115]:
#Split for REGRESSION
X = df.drop('Total_Amount', axis=1)
y = df['Total_Amount']

In [116]:
print("SHAPE OF X: ",X.shape)
print("SHAPE OF Y: ",y.shape)

SHAPE OF X:  (5000, 14)
SHAPE OF Y:  (5000,)

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [117]:
print("SHAPE OF X_train: ",X_train.shape)
print("SHAPE OF X_test: ",X_test.shape)
print("SHAPE OF Y_train: ",y_train.shape)
print("SHAPE OF Y_test: ",y_test.shape)

SHAPE OF X_train:  (4000, 14)
SHAPE OF X_test:  (1000, 14)
SHAPE OF Y_train:  (4000,)
SHAPE OF Y_test:  (1000,)

**Linear** **Regression** **Model**

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
lr.score(X_test,y_test)

0.7393186040780809

In [ ]:
y_pred_lr = lr.predict(X_test)

In [118]:
print("Linear Regression")
print("R2 Score:", r2_score(y_test, y_pred_lr))
print("MSE:", mean_squared_error(y_test, y_pred_lr))
print("MAE:", mean_absolute_error(y_test, y_pred_lr))

Linear Regression
R2 Score: 0.7393186040780809
MSE: 568215.3956610961
MAE: 468.7053430844594

**POLYNOMIAL** **REGRESSION**

In [ ]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

In [ ]:
poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

LinearRegression()

In [ ]:
y_pred_poly = poly_model.predict(X_test_poly)

In [119]:
print("Polynomial Regression")
print("R2 Score:", r2_score(y_test, y_pred_poly))
print("MSE:", mean_squared_error(y_test, y_pred_poly))
print("MAE:", mean_absolute_error(y_test, y_pred_poly))

Polynomial Regression
R2 Score: 1.0
MSE: 1.117529786602828e-22
MAE: 5.613083331468261e-12

**DECISION** **TREE** **REGRESSOR**

In [ ]:
dt=DecisionTreeRegressor()
dt.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
dt.score(X_test,y_test)

0.9956699911103902

In [ ]:
sc=StandardScaler()

In [ ]:
sc.fit(X_train)

StandardScaler()

In [ ]:
X_train_sc=sc.transform(X_train)
X_test_sc=sc.transform(X_test)

In [ ]:
y_pred_dt = dt.predict(X_test)

In [120]:
print("Decision Tree Regressor")
print("R2 Score:", r2_score(y_test, y_pred_dt))
print("MSE:", mean_squared_error(y_test, y_pred_dt))
print("MAE:",mean_absolute_error(y_test, y_pred_dt))

Decision Tree Regressor
R2 Score: 0.9979825042592423
MSE: 4397.598595500001
MAE: 22.873810000000006

**RANDOM FOREST REGRESSOR**

In [ ]:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

In [121]:
rf.score(X_test,y_test)

0.9974308161012996

In [122]:
y_pred_rf = rf.predict(X_test)

In [123]:
print("Random Forest Regressor")
print("R2 Score:", r2_score(y_test, y_pred_rf))
print("MSE:", mean_squared_error(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

Random Forest Regressor
R2 Score: 0.9974308161012996
MSE: 5600.130536217651
MAE: 19.528416799999977

**KNN REGRESSOR**

In [125]:
r2_scores = {}

for k in range(1, 31):
    knn = KNeighborsRegressor(n_neighbors=k, weights='distance')
    knn.fit(X_train_sc, y_train)
    y_pred = knn.predict(X_test_sc)
    r2 = r2_score(y_test, y_pred)
    r2_scores[k] = r2

best_k = max(r2_scores, key=r2_scores.get)
print("Best k:", best_k)
print("Best R2:", r2_scores[best_k])

Best k: 4
Best R2: 0.7339081078202687

In [126]:
knn_final = KNeighborsRegressor(n_neighbors=best_k, weights='distance')
knn_final.fit(X_train_sc, y_train)

KNeighborsRegressor(n_neighbors=4, weights='distance')

In [127]:
y_pred_knn = knn_final.predict(X_test_sc)

In [128]:
print("KNN Regressor")
print("R2 Score:", r2_score(y_test, y_pred_knn))
print("MSE:", mean_squared_error(y_test, y_pred_knn))
print("MAE:", mean_absolute_error(y_test, y_pred_knn))

KNN Regressor
R2 Score: 0.7339081078202687
MSE: 580008.8236538495
MAE: 416.08663719047024